"""initial schema

Revision ID: 66a3679b3e96
Revises: 
Create Date: 2026-05-17 12:46:20.169745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a3679b3e96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_country'), ['country'], unique=False)
        batch_op.create_index('ix_employees_country_job_title', ['country', 'job_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_job_title'), ['job_title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_job_title'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.drop_index('ix_employees_country_job_title')
        batch_op.drop_index(batch_op.f('ix_employees_country'))

    op.drop_table('employees')
    # ### end Alembic commands ###
